### ISSUE TITLE
Hyperion 2.0 Support

### ISSUE THREAD

**Issue by Apollo16** [firsttris/homebridge-hyperion-light#10]
Hey,

would be nice if you could add Hyperion 2.0 support. You have to change the "hyperion-js-api" since the api of hyperion-remote has changed. Would be great since Hyperion 2.0 ambilight engine looks quite a bit more polished

**Comment by firsttris** [comment]
Is there a API Specification for Hyperion 2.0 ?

**Comment by Apollo16** [comment]
Not documented, I'll compile it and document the json commands. Hyperion 'ng' 2.0 is almost complete but due to a lack of dev's the development is frozen atm.

**Comment by firsttris** [comment]
nice, if you are providing the json commands - i will update it.
thx

**Comment by Apollo16** [comment]
Sorry, i've wasted your time, the Hyperion-ng remote is quite bugged, I've had problems switching back to the V4L device after I set the LED colour :(

Here are the json commands if you need them in the future.

`{"color":[0,0,0],"command":"color","origin":"hyperion-remote","priority":50}
{"command":"componentstate","componentstate":{"component":"LEDDEVICE","state":false}}
{"command":"componentstate","componentstate":{"component":"LEDDEVICE","state":true}}
{"command":"clearall"}
{"command":"componentstate","componentstate":{"component":"V4L","state":true}}
{"command":"componentstate","componentstate":{"component":"V4L","state":false}}
{"command":"componentstate","componentstate":{"component":"ALL","state":false}}
{"command":"componentstate","componentstate":{"component":"ALL","state":true}}
`
