### ISSUE TITLE
error

### ISSUE THREAD

**Issue by qwikser** [firsttris/homebridge-hyperion-light#2]
Nach dem Update wegen den Effects - hab ich jetzt das hier ^^

`
/usr/lib/node_modules/homebridge-hyperion-light/hyperion.js:76
    ledState = data.info.activeLedColor.length > 0;
                                       ^

TypeError: Cannot read property 'length' of undefined
    at verifyLightState (/usr/lib/node_modules/homebridge-hyperion-light/hyperion.js:76:40)
    at send (/usr/lib/node_modules/homebridge-hyperion-light/hyperion.js:174:9)
    at Socket.client.on (/usr/lib/node_modules/homebridge-hyperion-light/hyperion.js:61:13)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

**Comment by firsttris** [comment]
Hallo...

scheint ja fast als würde dein hyperion einen andere antwort geben wie meines - wenn man nach der "serverInfo" frägt.

Ich hab den code mal etwas geändert.. kannst es nach einem Update nochmal versuchen.

außerdem wird nun die Antwort von Hyperion in die Log geschrieben.
Bei mir sieht die Antwortwie folgt aus, Kannst du mal deine Posten?

Hyperion Response: {"info":{"activeEffects":[],"activeLedColor":[],"adjustment":[{"blueAdjust":[0,0,255],"greenAdjust":[0,255,0],"id":"default","redAdjust":[255,0,0]}],"correction":[{"correctionValues":[255,255,255],"id":"default"}],"effects":[{"args":{"color-end":[238,173,47],"color-start":[136,97,7],"fade-time":5},"name":"Cinema brighten lights","script":"/storage/.kodi/addons/service.hyperion/effects/fade.py"},{"args":{"color-end":[136,97,7],"color-start":[238,173,47],"fade-time":5},"name":"Cinema dim lights","script":"/storage/.kodi/addons/service.hyperion/effects/fade.py"},{"args":{"color":[255,0,0],"fadeFactor":0.7,"speed":1},"name":"Knight rider","script":"/storage/.kodi/addons/service.hyperion/effects/knight-rider.py"},{"args":{"blobs":5,"color":[0,0,255],"hueChange":60,"reverse":false,"rotationTime":60},"name":"Blue mood blobs","script":"/storage/.kodi/addons/service.hyperion/effects/mood-blobs.py"},{"args":{"baseChange":true,"baseColorChangeRate":2,"baseColorRangeLeft":160,"baseColorRangeRight":320,"blobs":5,"color":[0,0,255],"hueChange":30,"reverse":false,"rotationTime":60},"name":"Cold mood blobs","script":"/storage/.kodi/addons/service.hyperion/effects/mood-blobs.py"},{"args":{"baseChange":true,"baseColorChangeRate":0.2,"baseColorRangeLeft":0,"baseColorRangeRight":360,"blobs":5,"colorRandom":true,"hueChange":30,"reverse":false,"rotationTime":60},"name":"Full color mood blobs","script":"/storage/.kodi/addons/service.hyperion/effects/mood-blobs.py"},{"args":{"blobs":5,"color":[0,255,0],"hueChange":60,"reverse":false,"rotationTime":60},"name":"Green mood blobs","script":"/storage/.kodi/addons/service.hyperion/effects/mood-blobs.py"},{"args":{"blobs":5,"color":[255,0,0],"hueChange":60,"reverse":false,"rotationTime":60},"name":"Red mood blobs","script":"/storage/.kodi/addons/service.hyperion/effects/mood-blobs.py"},{"args":{"baseChange":true,"baseColorChangeRate":2,"baseColorRangeLeft":333,"baseColorRangeRight":151,"blobs":5,"color":[255,0,0],"hueChange":30,"reverse":false,"rotationTime":60},"name":"Warm mood blobs","script":"/storage/.kodi/addons/service.hyperion/effects/mood-blobs.py"},{"args":{"color_one":[255,0,0],"color_two":[0,0,255],"colors_count":10,"reverse":false,"rotation-time":1.5},"name":"Police Lights Single","script":"/storage/.kodi/addons/service.hyperion/effects/police.py"},{"args":{"color_one":[255,0,0],"color_two":[0,0,255],"reverse":false,"rotation-time":1},"name":"Police Lights Solid","script":"/storage/.kodi/addons/service.hyperion/effects/police.py"},{"args":{"brightness":1,"reverse":false,"rotation-time":60},"name":"Rainbow mood","script":"/storage/.kodi/addons/service.hyperion/effects/rainbow-mood.py"},{"args":{"brightness":1,"reverse":false,"rotation-time":3},"name":"Rainbow swirl fast","script":"/storage/.kodi/addons/service.hyperion/effects/rainbow-swirl.py"},{"args":{"brightness":1,"reverse":false,"rotation-time":20},"name":"Rainbow swirl","script":"/storage/.kodi/addons/service.hyperion/effects/rainbow-swirl.py"},{"args":{"saturation":1,"speed":1},"name":"Random","script":"/storage/.kodi/addons/service.hyperion/effects/random.py"},{"args":{"colorLevel":230,"speed":1.5,"whiteLevel":100},"name":"Running dots","script":"/storage/.kodi/addons/service.hyperion/effects/running_dots.py"},{"args":{"alarm-color":[255,0,0],"post-color":[255,174,11],"shutdown-enabled":false,"speed":1.2},"name":"System Shutdown","script":"/storage/.kodi/addons/service.hyperion/effects/shutdown.py"},{"args":{"color":[255,0,0],"percentage":10,"rotation-time":12},"name":"Snake","script":"/storage/.kodi/addons/service.hyperion/effects/snake.py"},{"args":{"brightness":1,"color":[255,255,255],"random-color":true,"reverse":false,"rotation-time":3,"saturation":1,"sleep-time":0.05},"name":"Sparks Color","script":"/storage/.kodi/addons/service.hyperion/effects/sparks.py"},{"args":{"brightness":1,"color":[255,255,255],"random-color":false,"reverse":false,"rotation-time":3,"saturation":1,"sleep-time":0.05},"name":"Sparks","script":"/storage/.kodi/addons/service.hyperion/effects/sparks.py"},{"args":{"color":[0,0,255],"frequency":10},"name":"Strobe blue","script":"/storage/.kodi/addons/service.hyperion/effects/strobe.py"},{"args":{"color":[188,17,66],"frequency":10},"name":"Strobe Raspbmc","script":"/storage/.kodi/addons/service.hyperion/effects/strobe.py"},{"args":{"color":[255,255,255],"frequency":10},"name":"Strobe white","script":"/storage/.kodi/addons/service.hyperion/effects/strobe.py"},{"args":{"speed":1},"name":"Color traces","script":"/storage/.kodi/addons/service.hyperion/effects/traces.py"},{"args":{"ListenIP":"239.255.28.01","ListenPort":2801},"name":"UDP multicast listener","script":"/storage/.kodi/addons/service.hyperion/effects/udp.py"},{"args":{"ListenPort":2391},"name":"UDP listener","script":"/storage/.kodi/addons/service.hyperion/effects/udp.py"},{"args":{"sleepTime":0.75},"name":"X-Mas","script":"/storage/.kodi/addons/service.hyperion/effects/x-mas.py"}],"hostname":"LibreELEC","hyperion_build":[{"time":"Nov 21 2016 09:18:30","version":"355a324"}],"priorities":[{"duration_ms":116,"priority":890}],"temperature":[{"correctionValues":[255,255,255],"id":"default"}],"transform":[{"blacklevel":[0,0,0],"gamma":[2.5,2.5,2.5],"id":"default","luminanceGain":1,"luminanceMinimum":0,"saturationGain":1,"saturationLGain":1,"threshold":[0,0,0],"valueGain":1,"whitelevel":[1,1,1]}]},"success":true}

**Comment by qwikser** [comment]
Jetzt ist es gerannt bis ich die APP auf dem iPhone öffnete:

Hyperion Response: {"info":{"correction":[{"correctionValues":[255,235,240],"id":"default"}],"effects":[{"args":{"color-end":[238,173,47],"color-start":[136,97,7],"fade-time":5},"name":"Cinema brighten lights","script":"/storage/hyperion/effects/fade.py"},{"args":{"color-end":[136,97,7],"color-start":[238,173,47],"fade-time":5},"name":"Cinema dim lights","script":"/storage/hyperion/effects/fade.py"},{"args":null,"name":"","script":"/storage/hyperion/effects/"},{"args":{"color":[255,0,0],"fadeFactor":0.7,"speed":1},"name":"Knight rider","script":"/storage/hyperion/effects/knight-rider.py"},{"args":{"blobs":5,"color":[0,0,255],"hueChange":60,"reverse":false,"rotationTime":60},"name":"Blue mood blobs","script":"/storage/hyperion/effects/mood-blobs.py"},{"args":{"baseChange":true,"baseColorChangeRate":2,"baseColorRangeLeft":160,"baseColorRangeRight":320,"blobs":5,"color":[0,0,255],"hueChange":30,"reverse":false,"rotationTime":60},"name":"Cold mood blobs","script":"/storage/hyperion/effects/mood-blobs.py"},{"args":{"baseChange":true,"baseColorChangeRate":0.2,"baseColorRangeLeft":0,"baseColorRangeRight":360,"blobs":5,"color":[0,0,255],"hueChange":30,"reverse":false,"rotationTime":60},"name":"Full color mood blobs","script":"/storage/hyperion/effects/mood-blobs.py"},{"args":{"blobs":5,"color":[0,255,0],"hueChange":60,"reverse":false,"rotationTime":60},"name":"Green mood blobs","script":"/storage/hyperion/effects/mood-blobs.py"},{"args":{"blobs":5,"color":[255,0,0],"hueChange":60,"reverse":false,"rotationTime":60},"name":"Red mood blobs","script":"/storage/hyperion/effects/mood-blobs.py"},{"args":{"baseChange":true,"baseColorChangeRate":2,"baseColorRangeLeft":333,"baseColorRangeRight":151,"blobs":5,"color":[255,0,0],"hueChange":30,"reverse":false,"rotationTime":60},"name":"Warm mood blobs","script":"/storage/hyperion/effects/mood-blobs.py"},{"args":{"color_one":[255,0,0],"color_two":[0,0,255],"colors_count":10,"reverse":false,"rotation-time":1.5},"name":"Police Lights Single","script":"/storage/hyperion/effects/police.py"},{"args":{"color_one":[255,0,0],"color_two":[0,0,255],"reverse":false,"rotation-time":1},"name":"Police Lights Solid","script":"/storage/hyperion/effects/police.py"},{"args":{"brightness":1,"reverse":false,"rotation-time":60},"name":"Rainbow mood","script":"/storage/hyperion/effects/rainbow-mood.py"},{"args":{"brightness":1,"reverse":false,"rotation-time":3},"name":"Rainbow swirl fast","script":"/storage/hyperion/effects/rainbow-swirl.py"},{"args":{"brightness":1,"reverse":false,"rotation-time":20},"name":"Rainbow swirl","script":"/storage/hyperion/effects/rainbow-swirl.py"},{"args":{"saturation":1,"speed":1},"name":"Random","script":"/storage/hyperion/effects/random.py"},{"args":{"colorLevel":230,"speed":1.5,"whiteLevel":100},"name":"Running dots","script":"/storage/hyperion/effects/running_dots.py"},{"args":{"alarm-color":[255,0,0],"post-color":[255,174,11],"shutdown-enabled":false,"speed":1.2},"name":"System Shutdown","script":"/storage/hyperion/effects/shutdown.py"},{"args":{"color":[255,0,0],"percentage":10,"rotation-time":12},"name":"Snake","script":"/storage/hyperion/effects/snake.py"},{"args":{"brightness":1,"color":[255,255,255],"random-color":true,"reverse":false,"rotation-time":3,"saturation":1,"sleep-time":0.05},"name":"Sparks Color","script":"/storage/hyperion/effects/sparks.py"},{"args":{"brightness":1,"color":[255,255,255],"random-color":false,"reverse":false,"rotation-time":3,"saturation":1,"sleep-time":0.05},"name":"Sparks","script":"/storage/hyperion/effects/sparks.py"},{"args":{"color":[0,0,255],"frequency":10},"name":"Strobe blue","script":"/storage/hyperion/effects/strobe.py"},{"args":{"color":[188,17,66],"frequency":10},"name":"Strobe Raspbmc","script":"/storage/hyperion/effects/strobe.py"},{"args":{"color":[255,255,255],"frequency":10},"name":"Strobe white","script":"/storage/hyperion/effects/strobe.py"},{"args":{"speed":1},"name":"Color traces","script":"/storage/hyperion/effects/traces.py"},{"args":{"udpPort":2391},"name":"UDP listener","script":"/storage/hyperion/effects/udp.py"},{"args":{"sleepTime":0.75},"name":"X-Mas","script":"/storage/hyperion/effects/x-mas.py"}],"hostname":"kodiW","priorities":[{"duration_ms":164,"priority":900}],"temperature":[{"correctionValues":[255,255,255],"id":"default"}],"transform":[{"blacklevel":[0,0,0],"gamma":[1,1,1],"id":"default","luminanceGain":1,"saturationGain":1,"saturationLGain":1,"threshold":[0,0,0],"valueGain":1,"whitelevel":[1,1,1]}]},"success":true}

**Comment by firsttris** [comment]
Also es sollte noch immer laufen oder? Es hat ja nur die log in die Console geschrieben...

Kann es sein das du eine ältere hyperion version hast?
In der Antwort von Hyperion fehlt der aktuelle Status den das Licht gerade hat:

"info":{"activeEffects":[],"activeLedColor":[],"adjustment":[{"blueAdjust":[0,0,255],"greenAdjust":[0,255,0],"id":"default","redAdjust":[255,0,0]}]

Deshalb kam auch der Fehler - activeLedColor ist nicht vorhanden...

Ich habe Librelec v7.90.010 auf dem Raspberry Pi installiert. Da ist Hyperion als Kodi-Addon Integriert.

Grüße

**Comment by qwikser** [comment]
Hab OpenElec 6. irgendwas installiert - ist schon ein wenig her - Hyperion musste ich damals selber nachinstallieren. Mit der anderen PlugIn ohne das -light für die bridge - läuft es aber ohne Probleme.
Würde es ja updaten kodi/hyperion - aber 1,5h bevor football anfängt & da meine kodis alle an einer sql hängen & ich somit 5 stck. updaten müsste, muss ich das leider vertagen.. 🗡 

mfg.

**Comment by firsttris** [comment]
Bei einer älteren Openelec Version kannst du hyperion auch manuell übers terminal aktualisieren.
https://hyperion-project.org/wiki/Installation-with-command-line
Je nachdem wie alt deine config file ist solltest die auch neu generieren...

Die API wurde mal für die Iphone App erweitert... 

Kannst mir ja feedback geben...

Grüße

**Comment by firsttris** [comment]
Hallo
habe eine neue version mit besserem Fehlerhandling veröffentlicht.. 
habe das mit dem effect auch rausgeworfen - overkill.
Falls du noch immer Fehler hast erstelle einfach einen neuen Issue.

Grüße
