### ISSUE TITLE
HomeApp always shows Ambilight on when first loading

### ISSUE THREAD

**Issue by pdemarco925** [firsttris/homebridge-hyperion-light#6]
Hi,

Great work. I just have one odd problem.
When I first load the HomeApp it shows the Ambilight switch as on even though it is off. I can then control it properly. Each time I start the HomeApp it again shows it as on. Are you experiencing this?

**Comment by firsttris** [comment]
Hey,

problem is the hyperion-api has actually no method to check the ambilight status correctly.

There other open Issue is about the same problem. (but in german)

Here is the corresponding issue on hyperion repo:
https://github.com/hyperion-project/hyperion/issues/738#issuecomment-275146910

regards
Tristan

**Comment by pdemarco925** [comment]
Thanks for the reply and reference. I'll watch the hyperion repo as well and close this.

BTW, I ended up just commenting out the get method so the HomeApp defaults to off when started. The HomeApp then tracks on/off correctly (since it assumes success of a command). Obviously not a solution for it, but will end up being 'correct' more often for my usage.

Thanks
Paul

**Comment by mitch7391** [comment]
@pdemarco925 how did you go about commenting out the get method?

**Comment by pdemarco925** [comment]
Comment out lines 97-99
//            })
//            .on('get', (callback) => {
//                this.hyperion.getAmbiState(callback);

**Comment by mitch7391** [comment]
@pdemarco925 cheers for that mate :) and which file was it?

**Comment by pdemarco925** [comment]
index.js
The specific location will depend upon your config, but something like: "/usr/lib/node_modules/homebridge-hyperion-light/index.js" or "/opt/node/lib/..."

**Comment by mitch7391** [comment]
Perfect :) I did see that file, this should calm the perfectionist in me haha thanks so much!
